djangocrud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    task, 
    create_task,
    delete_task, 
    
    usuarios, 
    create_user,
    delete_user,
    
    list_products, 
    create_product,
    delete_product,
    
    list_teachers,
    create_teacher,
    delete_profesor
    )

app_name = 'tareas'

urlpatterns = [
    path('', task, name="task"),
    path('new/', create_task, name='create_task'),
    path('delete_task/<int:task_id>', delete_task, name='delete_task'),
    
    path('user/', usuarios, name="user"),
    path('user/create', create_user, name='create_user'),
    path('delete_user/<int:user_id>', delete_user, name='delete_user'),
    
    path('products/', list_products, name='list_products'),
    path('products/create', create_product, name='create_product'),
    path('delete_products/<int:product_id>', delete_product, name='delete_product'),
    
    path('profesor/', list_teachers, name="list_teachers"),
    path('profesor/create', create_teacher, name='create_teacher'),
    path('delete_profesor/<int:profesor_id>', delete_profesor, name='delete_profesor'),
]

tasks/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    
    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'
    
class User(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    
    def __str__(self) -> str:
        return self.username
    
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

def product_image_path(instance, filename):
    return f'static/img/{filename}'
        
class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to=product_image_path, blank=True)
    price = models.FloatField()
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        
class Profesor(models.Model):
    name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    sueldo = models.FloatField()
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Profesor'
        verbose_name_plural = 'Profesores'

tasks/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Profesor, Task, User, Product


# Create your views here.
def task(request):
    tasks = Task.objects.all()
    return render(request, 'list_task.html', {'tasks': tasks})

def create_task(request):
    task = Task(title=request.POST['title'], description=request.POST['description'])
    task.save()
    return redirect(reverse('tareas:task'))

def delete_task(_request, task_id):
    task = Task.objects.get(id=task_id)
    task.delete()
    return redirect('/tasks/')

# usuarios
def usuarios(request):
    users = User.objects.all()
    return render(request, 'user_form.html', {'users': users})

def create_user(request):
    user = User(username=request.POST['username'], password=request.POST['password'])
    user.save()
    return redirect('/tasks/user/')

def delete_user(_request, user_id):
    user = User.objects.get(id=user_id)
    user.delete()
    return redirect('/tasks/user/')

# productos
def list_products(request):
    productos = Product.objects.all()
    return render(request, 'list_product.html', {'productos': productos})

def create_product(request):
    name = request.POST['name']
    description = request.POST['description']
    price = request.POST['price']
    image = request.FILES['image']
    
    product = Product(name=name, description=description, price=price, image=image)
    
    product.save()
    return redirect('/tasks/products/')

def delete_product(_request, product_id):
    product = Product.objects.get(id=product_id)
    product.delete()
    return redirect('/tasks/products/')

# Profesores
def list_teachers(request):
    profesores = Profesor.objects.all()
    return render(request, 'profesores.html', {'profesores':profesores})

def create_teacher(request):
    teacher = Profesor(name=request.POST['name'], last_name=request.POST['last_name'], sueldo=request.POST['sueldo'])
    teacher.save()
    return redirect('/tasks/profesor/')

def delete_profesor(_request, profesor_id):
    profesor = Profesor.objects.get(id=profesor_id)
    profesor.delete()
    return redirect('/tasks/profesor/')

tasks/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'estilos.css' %}">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body>
    {% include 'parts/navbar.html' %}
    
    {% block content %}
        
    {% endblock content %}
        
</body>
</html>

tasks/templates/list_product.html
{% extends 'layout.html' %}

{% block title %}
    Productos
{% endblock title %}

{% block content %}
    
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h1 class="display-6 fw-bold text-center">Poductos aqui</h1>
                <form action="{% url 'tareas:create_product' %}" method="POST" enctype="multipart/form-data" class="card card-body bg-dark-subtle">
                    {% csrf_token %}
                    <input type="text" name="name" placeholder="Nombre del producto" class="form-control mb-2">
                    <textarea name="description" rows="5" placeholder="Escribe aqui la descripcion" class="form-control mb-2"></textarea>
                    <input type="numbre" name="price" placeholder="precio del producto" class="form-control mb-2">
                    <input type="file" name="image" class="text-black">
                    <button class="btn btn-success mt-2">Guardar</button>
                </form>

                
                {% for producto in productos %}
                    <div class="card card-body text-black mt-2">
                        <img src="{{ producto.image.url }}" alt="{{ producto.name }}" class="card-img-top">
                        <div class="card-body bg-success">
                            <h2 class="card-title">{{ producto.name }}</h2>
                            <p class="card-text">{{ producto.description }}</p>
                            <p class="card-text fw-bold">Price: {{ producto.price }}</p>
                        </div>
                        <div class="card-footer text-end">
                            <form action="{% url 'tareas:delete_product' producto.id %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-danger btn-sm">Delete</button>
                            </form>
                        </div>
                    </div>
                {% empty %}
                    <div class="alert alert-info mt-2">Ningún producto registrado</div>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock content %}

tasks/templates/list_task.html
{% extends 'layout.html' %}

{% block title %}
    Tareas
{% endblock title %}


{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <h1 class="display-6 fw-bold">Listas de tareas</h1>
                <form action="{% url 'tareas:create_task' %}" method="POST" class="card card-body bg-secondary">
                    {% csrf_token %}
                    <label for="title">Titulo:</label>
                    <input type="text" name="title" placeholder="Escribe el titulo" class="form-control mb-2">

                    <label for="description">Descripcion:</label>
                    <textarea name="description" rows="3" placeholder="Escribe la descripcion" class="form-control mb-2"></textarea>
                    <button class="btn btn-success">Save</button>
                </form>
            
                {% for task in tasks %}
                    <div class="card card-body text-black mt-2 d-flex flex-row justify-content-between">
                        <div>
                            <h3>{{ task.title }}</h3>
                            <p>{{ task.description }}</p>
                        </div>
                        <form action="{% url 'tareas:delete_task' task.id %}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </div>
                {% empty %}
                    <h3 class="mt-3">No hay tareas que mostrar</h3>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

tasks/templates/parts/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
        <a class="navbar-brand fw-bold fst-italic" href="{% url 'tareas:task' %}">TAREAS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tareas:user' %}">Usuarios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tareas:list_teachers' %}">Profesores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tareas:list_products' %}">Productos</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

tasks/templates/profesores.html
{% extends 'layout.html' %}


{% block title %}
    Profesores
{% endblock title %}


{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h1 class="display-6 fw-bold text-white text-center">Profesores</h1>
                <form action="{% url 'tareas:create_teacher' %}" method="POST" class="card card-body bg-body-secondary">
                    {% csrf_token %}
                    <input type="text" name="name" placeholder="Escribe el nombre" class="form-control mb-2">
                    <input type="text" name="last_name" placeholder="Escribe el apellido" class="form-control mb-2">
                    <input type="number" name="sueldo" placeholder="Escribe el salario" class="form-control mb-2">
                    <button class="btn btn-success mt-2">Save</button>
                </form>

                
                {% for profesor in profesores %}
                    <div class="card card-body text-black mt-2 d-flex flex-row justify-content-between">
                        <div>
                            <h2>{{ profesor.name }}</h2>
                            <p>{{ profesor.last_name }}</p>
                            <p>{{ profesor.sueldo }}</p>
                        </div>
                        <form action="{% url 'tareas:delete_profesor' profesor.id %}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-danger my-5">Delete</button>
                        </form>
                    </div>
                {% empty %}
                    <h2>Ningun profesor registrado</h2>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

tasks/templates/user_form.html
{% extends 'layout.html' %}


{% block title %}
    Usuarios
{% endblock title %}


{% block content %}

    <div class="container ">
        <div class="row">
            <div class="col-md-6 offset-md-3 mt-2 text-black">
                    <h1 class="display-6 fw-bold text-center text-white">Usuarios</h1>
                    <form action="{% url 'tareas:create_user' %}" method="POST" class="card card-body bg-dark-subtle">
                        {% csrf_token %}
                        <input type="text" name="username" placeholder="username" class="form-control mb-2">
                        <input type="password" name="password" placeholder="password" class="form-control mb-2">
                        <button class="btn btn-success">Guardar</button>
                    </form>

                    {% for user in users %}
                        <div class="card card-body text-black mt-2 d-flex flex-row justify-content-between">
                            <div>
                                <h2>{{ user.username }}</h2>
                                <h3>{{ user.password }}</h3>
                            </div>
                            <form action="{% url 'tareas:delete_user' user.id %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-danger btn-sm my-4">Delete</button>
                            </form>
                        </div>
                    {% empty %}
                        <h2>No hay usuarios registrados</h2>
                    {% endfor %}
            </div>
        </div>
    </div>

    
    

{% endblock content %}